### ISSUE TITLE
Stylelint modules description

### ISSUE THREAD

**Issue by vlad-yaremenko** [vlad-yaremenko/front-end-specification#18]
Отсутствует описание для модулей
- stylelint-z-index-value-constraint 
- stylelint-declaration-strict-value

Нужно добавить к списку [тут](https://github.com/vlad-yaremenko/front-end-specification#styles)

**Comment by Alevettih** [comment]
Добавил тут: https://github.com/vlad-yaremenko/front-end-specification/pull/20
