### ISSUE TITLE
Team code conventions, forms handling, table of contents

### ISSUE THREAD

**Issue by kostyanet** [vlad-yaremenko/front-end-specification#22]
Предлагаю сразу несколько вещей добавить в спецификацию:
1) Соглашения по стилю кода в Requestum front-end team, куда можно вносить вещи, принятые в JS-сообществе, но не отраженные в официальных style guide вроде Air BnB, или [Angular](https://angular.io/guide/styleguide), ссылку на который можно также привести в спецификации. Например, предлагается именовать поля классов (компонентов), указывающих на асинхронные сущности с суффиксом `$`, как это принято в Angular community. Это могут быть Promise, Observable, EventEmmiter, Subject и т.п.
![image](https://user-images.githubusercontent.com/21313651/39957395-2e660936-55fb-11e8-8810-50f151360856.png)
2) Сделать руководство по работе с формами. Например, такие рекомендации:
- использовать .trim()
- предупреждать о несохраненных данных при переходе на другую страницу
- валидировать где это возможно (телефоны, email, цены, имена -- numbers\alphabetics only)
- фильтровать ввод на предмет опасных символов `> < * &`
- прочее
(Постараюсь с прошлой работы попросить свой труд на эту тему)
3) Руководству не хватает Содержания))

**Comment by vlad-yaremenko** [comment]
> Сделать руководство по работе с формами. Например, такие рекомендации:

Согласен, это можно внести в [Good breeding](https://github.com/vlad-yaremenko/front-end-specification#good-breeding). 

Можно даже создать отдельный файл и приложить ссылку, если много инфы.

**Comment by vlad-yaremenko** [comment]
> Руководству не хватает Содержания))

1. Это не последний вариант и есть еще планы и таски я это уже шарил
2. Как я уже писал
> Feel free to create pull requests to add content. Open issues to discuss ideas, or get clarification.

**Comment by vlad-yaremenko** [comment]
> Соглашения по стилю кода в Requestum front-end team

Предлагаю приложить короткое описание в JavaScript > Style guide и добавить ссылку на файл, где и будем все вносить

**Comment by vlad-yaremenko** [comment]
https://github.com/vlad-yaremenko/front-end-specification/pull/23
