### ISSUE TITLE
BEM Modifier

### ISSUE THREAD

**Issue by oksanamuz** [vlad-yaremenko/front-end-specification#26]
Lets discuss what type of the modifier we should use: yandex (block_modifier) или american style (block--modifier)

**Comment by vlad-yaremenko** [comment]
yandex +1

**Comment by kostyanet** [comment]
Второй явно читабельней

**Comment by andrhome** [comment]
2-ой +

**Comment by oksanamuz** [comment]
yandex +1

**Comment by kostyanet** [comment]
Аргументы:
1) бэк-енд любит snake case -- предлагаю им его и оставить
2) один символ на уровне baseline, т.е. _ читается хуже и заметен менее, чем два символа на "уровне глаз", т.е. --
3) подчеркивание можно не отличить от пробела при беглом чтении кода

**Comment by Alevettih** [comment]
Yandex +1

**Comment by valeriiahryhorieva** [comment]
Yandex +

**Comment by SamoilovKonstantin** [comment]
2-ой

**Comment by bezdna** [comment]
я за яндекс стиль, в том числе из-за того что на некоторых проектах бек-енд может спокойно лезть и во фронт-енд, и пусть они все пишут в одном стиле, и я иногда могу что-то поправить в бек-енде,
иногда попадаются такие динозавры когда PHP и JS в одном шаблоне и будет удобнее писать в одном стиле
2. аргумент за яндекс, методологию именования эту придумали они и большинство разработчиков читает русскую документацию и соответственно если переходить на инглишь вариант то будет новым людям частично непонятно почему так а не иначе. в свою очередь опытный разработчик может спокойно переключиться на другой вариант если в команде есть подобная договоренность.

**Comment by kostyanet** [comment]
Почему не оставить оба варианта? Это ж не такой принципиальный момент..

**Comment by oksanamuz** [comment]
> Почему не оставить оба варианта? Это ж не такой принципиальный момент..

Плохой вариант, человек делает себе проект, потом к нему подключают второго разраба, который пишет по другому и получается каша

**Comment by kostyanet** [comment]
Если человека подключают, то пусть он следует выбранному соглашению. Но на стадии зачатия проекта можно дать выбор

**Comment by oksanamuz** [comment]
> Если человека подключают, то пусть он следует выбранному соглашению. Но на стадии зачатия проекта можно дать выбор

Сужу по себе и думаю остальным тоже это знакомо, когда ты привык писать в однном стиле переключаться сложно прыгая с одного проекта на другой, теряется скорость потому, что ты задумываешься еще и над тем, как писать модификатор, да незначительно, но все же

**Comment by kostyanet** [comment]
Не хочу верить что обдумывание модификатора отнимает у кого-то время)))

**Comment by SamoilovKonstantin** [comment]
Когда это 27 подвид кнопки, отнимает...

**Comment by kostyanet** [comment]
Это фантастические измышления! Один два раза подсмотрел как уже именуется, запомнил и пошёл дальше. Это не сравнимо с переключением на другой фреймворк

**Comment by SamoilovKonstantin** [comment]
Я думаю, что Ксюша как раз об этом, типа из-за динамической смены проектов, где разные фреймворки, типы работы, мозг и так ломается, а еще и в таком вопросе тратить лишнее внимание (хоть какая-то помощь). Но это больше дело привычки) В целом, я за мнение большинства в данном вопросе, главное что бы всем удобно было:) А если хочется что-то применить, то лучше в своем проекте (где допустим несколько фронтов), а не сразу ко всему отделу, если всем сильно понравится, то у тебя уже будет не один голос свершить револьцию)

**Comment by SamoilovKonstantin** [comment]
P.S. В моем понимании лучше, что бы люди просто придерживались какой-то методологии, а не рандомные названия, вот это действительно ломает мозг)

**Comment by vlad-yaremenko** [comment]
Суть спеки в том, чтобы делать банальные вещи на автомате и не заставлять человека думать что и когда он будет использовать

**Comment by oksanamuz** [comment]
> А если хочется что-то применить, то лучше в своем проекте (где допустим несколько фронтов), а не сразу ко всему отделу, если всем сильно понравится, то у тебя уже будет не один голос свершить револьцию)

каждый из нас уже выбрал для себя вариант и смысла нету пробовать) кому-то нравится 1 кому-то другое. смысл в том, чтобы сейчас определиться в конце-концов и не морочить никому голову.  Части команды придется немного заморочиться и привыкнуть к новому написанию и на этом все, но это в любом случее лучше, чем каждый будет писать по свойму и тебе придется кадый раз подстраиваться под кого-то

**Comment by AlexVarenin** [comment]
american +

**Comment by andrhome** [comment]
Еще чем _ не удобно - наши бэк-ендщики часто называют переменные с _, типо: current_user_name, user_id, user_email и т.д. И тут мы еще со своими модификаторами btn_success, btn_big ... Получится каша.

**Comment by AlexVarenin** [comment]
html academy рекомендует american style, поэтому многим новичкам, которые используют этот ресурс для обучения будет ближе именно он

**Comment by Baskina** [comment]
запоздало, но все же:
yandex +

**Comment by vlad-yaremenko** [comment]
09eee5ab63a0b2881586edb9c37680d9996667b3
