### ISSUE TITLE
Selector pseudo element

### ISSUE THREAD

**Issue by oksanamuz** [vlad-yaremenko/front-end-specification#27]
Selector of pseudo elements should be with double colon. 

> The double colon replaced the single-colon notation for pseudo-elements in CSS3. This was an attempt from W3C to distinguish between pseudo-classes and pseudo-elements.
The single-colon syntax was used for both pseudo-classes and pseudo-elements in CSS2 and CSS1.
For backward compatibility, the single-colon syntax is acceptable for CSS2 and CSS1 pseudo-elements.

https://www.w3schools.com/css/css_pseudo_elements.asp

**Comment by vlad-yaremenko** [comment]
Я не против, можно заменить

**Comment by vlad-yaremenko** [comment]
https://github.com/vlad-yaremenko/front-end-specification/commit/81978da723d6c7758489d85b286d9cb6bd6bc24e
