### ISSUE TITLE
Список браузеров в stylelintrc

### ISSUE THREAD

**Issue by Alevettih** [vlad-yaremenko/front-end-specification#9]
Не уверен что есть необходимость перечислять браузеры внутри eslintrc, если мы их выносим в package.json
В связи с этим, объект с ключом "browsers" можно отсюда убрать:
```bash
"plugin/no-unsupported-browser-features": [
      true,
      {
        "browsers": [
          "> 2%",
          "Last 2 versions",
          "ie >= 10",
          "not ie_mob < 11",
          "not op_mini all"
        ],
        "severity": "warning"
      }
    ],
```
Либо можно настройки версий браузера вынести в файл "browserslist", по идее они должны подтягиваться везде, где они необходимы

**Comment by vlad-yaremenko** [comment]
Done here https://github.com/vlad-yaremenko/front-end-specification/commit/adee9073ec427c270cf730656debc2c6fcb7f149
